name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  backend:
    runs-on: windows-latest
    defaults:
      run:
        working-directory:  ./backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache backend node_modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: backend-node-${{ hashFiles('back-end/package-lock.json', 'back-end/package.json') }}
          restore-keys: |
            backend-node-

      - name: Install backend deps
        run: npm install

      - name: Run backend lint/tests
        run: npm run lint && npm test

  frontend:
    runs-on: windows-latest
    defaults:
      run:
        working-directory:  ./frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache frontend node_modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: frontend-node-${{ hashFiles('front-end/package-lock.json', 'front-end/package.json') }}
          restore-keys: |
            frontend-node-

      - name: Install frontend deps
        run: npm install

      - name: Run frontend lint/tests/build
        run: npm run lint && npm run test && npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: dist
